app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.4
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.nimeji.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Management:
            - Kanidm:
                href: https://auth.nimeji.com
                description: Identity management
                icon: https://auth.nimeji.com/pkg/img/logo-square.svg
          - Development:
            - ArgoCD:
                href: https://argocd.nimeji.com
                description: Continuous deployment
                icon: argocd.svg
            - Git:
                href: https://git.nimeji.com
                description: Gitea
                icon: gitea.svg
            - Grafana:
                href: https://grafana.nimeji.com
                description: Observability dashboards
                icon: grafana.svg
          - Apps:
            - Excalidraw:
                href: https://draw.nimeji.com
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.nimeji.com
                description: Internal network speed test
                icon: openspeedtest.png
            - Ai-Shop:
                href: https://ai-shop.nimeji.com
                desciption: Ai-Shop Project
        bookmarks.yaml: |
          - Homelab:
            - Repository:
              - href: https://github.com/nimeji/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
            - Zerotier:
              - href: https://my.zerotier.com
                icon: zerotier.svg
