apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-shop-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ai-shop-frontend
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: ai-shop-frontend
    spec:
      containers:
        - name: ai-shop-frontend
          image: git.nimeji.com/nimeji/ai-shop-frontend:{{ .Values.appVersion }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: ai-shop-frontend
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: ai-shop.nimeji.com
            - name: IMAGE_CDN_URL
              value: https://images.ai-shop.nimeji.com
            - name: PUBLIC_STORE_DOMAIN
              value: quickstart-be0c852d.myshopify.com
            - name: PUBLIC_STOREFRONT_API_TOKEN
              value: acbd231f90492b1833c47433122b1307
            - name: PUBLIC_CHECKOUT_DOMAIN
              value: checkout.quickstart-be0c852d.myshopify.com
            - name: SHOPIFY_APP_METAFIELD_NAMESPACE
              value: app--146622644225--printify
