apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-shop-frontend
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ai-shop-frontend
  data:
    - secretKey: PRIVATE_STOREFRONT_API_TOKEN
      remoteRef:
        key: /ai-shop/frontend
        property: PRIVATE_STOREFRONT_API_TOKEN
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /ai-shop/frontend
        property: SESSION_SECRET
