- name: Configure ports
  ufw:
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop:
    - port: 22
      proto: tcp
    - port: 30000
      proto: udp

# wireguard
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Enable ufw
  ufw:
    state: enabled