apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-shop-backend
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ai-shop-backend
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /ai-shop/db
        property: password
    - secretKey: GETIMG_SECRET
      remoteRef:
        key: /ai-shop/backend
        property: GETIMG_SECRET
    - secretKey: PRINTIFY_SECRET
      remoteRef:
        key: /ai-shop/backend
        property: PRINTIFY_SECRET
    - secretKey: PRINTIFY_WEBHOOK_SECRET
      remoteRef:
        key: /ai-shop/backend
        property: PRINTIFY_WEBHOOK_SECRET
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: /ai-shop/backend
        property: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: /ai-shop/backend
        property: S3_SECRET_ACCESS_KEY
    - secretKey: SHOPIFY_ACCESS_TOKEN
      remoteRef:
        key: /ai-shop/backend
        property: SHOPIFY_ACCESS_TOKEN
    - secretKey: SHOPIFY_CLIENT_ID
      remoteRef:
        key: /ai-shop/backend
        property: SHOPIFY_CLIENT_ID
    - secretKey: SHOPIFY_CLIENT_SECRET
      remoteRef:
        key: /ai-shop/backend
        property: SHOPIFY_CLIENT_SECRET