apiVersion: v1
kind: Service
metadata:
  name: ai-shop-backend
  labels:
    app: ai-shop-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ai-shop-backend
