- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - prerequisites
    - k3s
    # TODO enable automatic updates
    #- automatic_upgrade
- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium
