all:
  vars:
    control_plane_endpoint: 94.130.164.224
    load_balancer_ip_pool:
      - 94.130.164.224/32 
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 94.130.164.224, mac: '88:d7:f6:7c:2e:ca', disk: md, network_interface: enp6s0}
