all:
  vars:
    control_plane_endpoint: "2a01:4f8:13b:2769:1::"
    load_balancer_ip_pool:
      - "2a01:4f8:13b:2769:1::/32"
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 94.130.164.224, mac: '88:d7:f6:7c:2e:ca', disk: md, network_interface: enp6s0}
