---

- name: ensure nginx is at the latest version
  apt:
    name:
    - nginx
    - nginx-extras
    state: latest

- name: copy the nginx config file
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
