gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: &host git.nimeji.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.nimeji.com
        OFFLINE_MODE: true
      repository:
        DISABLED_REPO_UNITS: repo.wiki,repo.projects
        DISABLE_STARS: true
        DEFAULT_BRANCH: master
      service.explore:
        DISABLE_USERS_PAGE: true
      actions:
        ENABLED: true
      webhook:
        ALLOWED_HOST_LIST: private
  persistence:
    size: 50Gi
