apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-shop-db
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ai-shop-db
  data:
    - secretKey: postgres-password
      remoteRef:
        key: /ai-shop/db
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: /ai-shop/db
        property: password
