apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gitea.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: nimeji
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /gitea/admin
        property: password
