apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker-oauth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: key
      remoteRef:
        key: /gitea/woodpecker
        property: client_id
    - secretKey: secret
      remoteRef:
        key: /gitea/woodpecker
        property: client_secret
