# Registry
- path: registry/admin
  data:
    - key: password
      length: 32
      special: true
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true
- path: gitea/woodpecker
  data:
    - key: client_id
      length: 32
      special: false
    - key: client_secret
      length: 32
      special: false
- path: woodpecker/agent
  data:
      - key: secret
        length: 32
        special: false
