# Registry
- path: registry/admin
  data:
    - key: password
      length: 32
      special: true
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true
- path: ai-shop/db
  data:
    - key: postgres-password
      length: 32
      special: true
- path: ai-shop/db
  data:
    - key: password
      length: 32
      special: true
