apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: factorio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      restartPolicy: unless-stopped
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: factorio
          image: factoriotools/factorio:1.1.104
          ports:
            - containerPort: 34197
              protocol: UDP
            - containerPort: 27015
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /factorio
