apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: {{ .Release.Namespace }}
  labels:
    app: factorio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 34197
      protocol: UDP
  selector:
    app: factorio
