
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio
  namespace: {{ .Release.Namespace }}
  labels:
    app: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi